[id='assembly_business-processes-getting-started']

include::product-shared-docs/document-attributes.adoc[]

= Getting started with business processes
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: business-processes-getting-started
include::product-shared-docs/author-group.adoc[]

// Purpose statement for the assembly
As a business analyst, you can use {CENTRAL} in {PRODUCT} to design a variety of business processes. A business process is a graph that describes the order in which a series of steps need to be executed, using a flow chart.
A process consists of a collection of predefined node types that are linked to each other using connections.
Each of the nodes represents one step in the overall process while the connections specify how to transition from one node to the other.

.Prerequisites
* Installed {EAP_LONG} 7.1.0. See  https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/installation_guide/[_Red Hat JBoss EAP 7.1.0 Installation Guide_].
* Installed {PRODUCT}. For more information, see the {URL_INSTALLING_DM_ON_PREMISE}[{INSTALLING_DM_ON_PREMISE}].
* {PRODUCT} is running and you can log in to {CENTRAL} with the `admin` role. For more information, see the {URL_INSTALLING_DM_ON_PREMISE}[{INSTALLING_DM_ON_PREMISE}].

// Modules - concepts, procedures, refs, etc.

include::product-development-guide/chap-about-this-guide.adoc[leveloffset=+1]

include::product-user-guide/assets-business-processes-gloss.adoc[leveloffset=+1]

include::product-development-guide/chap-getting-started-with-processes.adoc[leveloffset=+1]


// Versioning info
include::product-shared-docs/versioning-information.adoc[]
