//Module included in the following assemblies:
//product-assembly_guided-decision-tables/../main.adoc
//product-assembly_guided-rules/../main.adoc
//product-assembly_guided-rule-templates/../main.adoc
//product-assembly-business-processes/../main.adoc

[id='data-objects-con_{context}']
= Data objects

Data objects are the building blocks for the rule assets that you create. Data objects are custom data types implemented as Java objects in specified packages of your project. For example, you might create a `Person` object with data fields `Name`, `Address`, and `DateOfBirth` to specify personal details for loan application rules. These custom data types determine what data your assets and your decision service are based on. *<MH>Cristiano, this is a boilerplate topic that we have been using to introduce DOs for other guides. I think that we need to reword this for the Case GSG. Do you agree? If so, can you provide a short intro for DOs as they pertain to case management business processes?</MH>*
